name: inline_dialogs
description: A simple Flutter package to implement inline dialogs which can be managed from the main program context. The dialog can be closed from the same code from which it was invoked.
version: 1.0.1
homepage: https://github.com/1SouravGhosh/flutter_inline_dialogs
repository: https://github.com/1SouravGhosh/flutter_inline_dialogs
issue_tracker: https://github.com/1SouravGhosh/flutter_inline_dialogs/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
